// Code generated by "stringer -type=HighGUID -trimprefix=HighGUID"; DO NOT EDIT.

package database

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HighGUIDItem-1073741824]
	_ = x[HighGUIDContainer-1073741824]
	_ = x[HighGUIDPlayer-0]
	_ = x[HighGUIDGameobject-4044357632]
	_ = x[HighGUIDTransport-4045406208]
	_ = x[HighGUIDUnit-4046454784]
	_ = x[HighGUIDPet-4047503360]
	_ = x[HighGUIDDynamicObject-4043309056]
	_ = x[HighGUIDCorpse-4043374592]
	_ = x[HighGUIDMoTransport-532676608]
}

const (
	_HighGUID_name_0 = "Player"
	_HighGUID_name_1 = "MoTransport"
	_HighGUID_name_2 = "Item"
	_HighGUID_name_3 = "DynamicObject"
	_HighGUID_name_4 = "Corpse"
	_HighGUID_name_5 = "Gameobject"
	_HighGUID_name_6 = "Transport"
	_HighGUID_name_7 = "Unit"
	_HighGUID_name_8 = "Pet"
)

func (i HighGUID) String() string {
	switch {
	case i == 0:
		return _HighGUID_name_0
	case i == 532676608:
		return _HighGUID_name_1
	case i == 1073741824:
		return _HighGUID_name_2
	case i == 4043309056:
		return _HighGUID_name_3
	case i == 4043374592:
		return _HighGUID_name_4
	case i == 4044357632:
		return _HighGUID_name_5
	case i == 4045406208:
		return _HighGUID_name_6
	case i == 4046454784:
		return _HighGUID_name_7
	case i == 4047503360:
		return _HighGUID_name_8
	default:
		return "HighGUID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
