// Code generated by "stringer -type=TypeID -trimprefix=TypeID"; DO NOT EDIT.

package database

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeIDObject-0]
	_ = x[TypeIDItem-1]
	_ = x[TypeIDContainer-2]
	_ = x[TypeIDUnit-3]
	_ = x[TypeIDPlayer-4]
	_ = x[TypeIDGameObject-5]
	_ = x[TypeIDDynamicObject-6]
	_ = x[TypeIDCorpse-7]
}

const _TypeID_name = "ObjectItemContainerUnitPlayerGameObjectDynamicObjectCorpse"

var _TypeID_index = [...]uint8{0, 6, 10, 19, 23, 29, 39, 52, 58}

func (i TypeID) String() string {
	if i < 0 || i >= TypeID(len(_TypeID_index)-1) {
		return "TypeID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TypeID_name[_TypeID_index[i]:_TypeID_index[i+1]]
}
