// Code generated by "stringer -type=AuthErrorCode"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AuthOK-12]
	_ = x[AuthFailed-13]
	_ = x[AuthReject-14]
	_ = x[AuthBadServerProof-15]
	_ = x[AuthUnavailable-16]
	_ = x[AuthSystemError-17]
	_ = x[AuthBillingError-18]
	_ = x[AuthBillingExpired-19]
	_ = x[AuthVersionMismatch-20]
	_ = x[AuthUnknownAccount-21]
	_ = x[AuthIncorrectPassword-22]
	_ = x[AuthSessionExpired-23]
	_ = x[AuthServerShuttingDown-24]
	_ = x[AuthAlreadyLoggingIn-25]
	_ = x[AuthLoginServerNotFound-26]
	_ = x[AuthWaitQueue-27]
	_ = x[AuthBanned-28]
	_ = x[AuthAlreadyOnline-29]
	_ = x[AuthNoTime-30]
	_ = x[AuthDbBusy-31]
	_ = x[AuthSuspended-32]
	_ = x[AuthParentalControl-33]
}

const _AuthErrorCode_name = "AuthOKAuthFailedAuthRejectAuthBadServerProofAuthUnavailableAuthSystemErrorAuthBillingErrorAuthBillingExpiredAuthVersionMismatchAuthUnknownAccountAuthIncorrectPasswordAuthSessionExpiredAuthServerShuttingDownAuthAlreadyLoggingInAuthLoginServerNotFoundAuthWaitQueueAuthBannedAuthAlreadyOnlineAuthNoTimeAuthDbBusyAuthSuspendedAuthParentalControl"

var _AuthErrorCode_index = [...]uint16{0, 6, 16, 26, 44, 59, 74, 90, 108, 127, 145, 166, 184, 206, 226, 249, 262, 272, 289, 299, 309, 322, 341}

func (i AuthErrorCode) String() string {
	i -= 12
	if i >= AuthErrorCode(len(_AuthErrorCode_index)-1) {
		return "AuthErrorCode(" + strconv.FormatInt(int64(i+12), 10) + ")"
	}
	return _AuthErrorCode_name[_AuthErrorCode_index[i]:_AuthErrorCode_index[i+1]]
}
