// Code generated by "stringer -type=Byte2Flags -trimprefix=Byte2Flags"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Byte2FlagsNone-0]
	_ = x[Byte2FlagsDetectAmore0-2]
	_ = x[Byte2FlagsDetectAmore1-4]
	_ = x[Byte2FlagsDetectAmore2-8]
	_ = x[Byte2FlagsDetectAmore3-16]
	_ = x[Byte2FlagsStealth-32]
	_ = x[Byte2FlagsInvisibilityGlow-64]
}

const (
	_Byte2Flags_name_0 = "None"
	_Byte2Flags_name_1 = "DetectAmore0"
	_Byte2Flags_name_2 = "DetectAmore1"
	_Byte2Flags_name_3 = "DetectAmore2"
	_Byte2Flags_name_4 = "DetectAmore3"
	_Byte2Flags_name_5 = "Stealth"
	_Byte2Flags_name_6 = "InvisibilityGlow"
)

func (i Byte2Flags) String() string {
	switch {
	case i == 0:
		return _Byte2Flags_name_0
	case i == 2:
		return _Byte2Flags_name_1
	case i == 4:
		return _Byte2Flags_name_2
	case i == 8:
		return _Byte2Flags_name_3
	case i == 16:
		return _Byte2Flags_name_4
	case i == 32:
		return _Byte2Flags_name_5
	case i == 64:
		return _Byte2Flags_name_6
	default:
		return "Byte2Flags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
