// Code generated by "stringer -type=Byte1Flags -trimprefix=Byte1Flags"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Byte1FlagsAlwaysStand-1]
	_ = x[Byte1FlagsCreep-2]
	_ = x[Byte1FlagsUntrackable-4]
	_ = x[Byte1FlagsAll-255]
}

const (
	_Byte1Flags_name_0 = "AlwaysStandCreep"
	_Byte1Flags_name_1 = "Untrackable"
	_Byte1Flags_name_2 = "All"
)

var (
	_Byte1Flags_index_0 = [...]uint8{0, 11, 16}
)

func (i Byte1Flags) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Byte1Flags_name_0[_Byte1Flags_index_0[i]:_Byte1Flags_index_0[i+1]]
	case i == 4:
		return _Byte1Flags_name_1
	case i == 255:
		return _Byte1Flags_name_2
	default:
		return "Byte1Flags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
