// Code generated by "stringer -type=CharacterFlag -trimprefix=CharacterFlag"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CharacterFlagNone-0]
	_ = x[CharacterFlagLockedForTransfer-4]
	_ = x[CharacterFlagHideHelm-1024]
	_ = x[CharacterFlagHideCloak-2048]
	_ = x[CharacterFlagGhost-8192]
	_ = x[CharacterFlagRename-16384]
	_ = x[CharacterFlagLockedByBilling-16777216]
	_ = x[CharacterFlagDeclined-33554432]
}

const (
	_CharacterFlag_name_0 = "None"
	_CharacterFlag_name_1 = "LockedForTransfer"
	_CharacterFlag_name_2 = "HideHelm"
	_CharacterFlag_name_3 = "HideCloak"
	_CharacterFlag_name_4 = "Ghost"
	_CharacterFlag_name_5 = "Rename"
	_CharacterFlag_name_6 = "LockedByBilling"
	_CharacterFlag_name_7 = "Declined"
)

func (i CharacterFlag) String() string {
	switch {
	case i == 0:
		return _CharacterFlag_name_0
	case i == 4:
		return _CharacterFlag_name_1
	case i == 1024:
		return _CharacterFlag_name_2
	case i == 2048:
		return _CharacterFlag_name_3
	case i == 8192:
		return _CharacterFlag_name_4
	case i == 16384:
		return _CharacterFlag_name_5
	case i == 16777216:
		return _CharacterFlag_name_6
	case i == 33554432:
		return _CharacterFlag_name_7
	default:
		return "CharacterFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
