// Code generated by "stringer -type=FoodType -trimprefix=FoodType"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FoodTypeMeat-1]
	_ = x[FoodTypeFish-2]
	_ = x[FoodTypeCheese-3]
	_ = x[FoodTypeBread-4]
	_ = x[FoodTypeFungas-5]
	_ = x[FoodTypeFruit-6]
	_ = x[FoodTypeRawMeat-7]
	_ = x[FoodTypeRawFish-8]
}

const _FoodType_name = "MeatFishCheeseBreadFungasFruitRawMeatRawFish"

var _FoodType_index = [...]uint8{0, 4, 8, 14, 19, 25, 30, 37, 44}

func (i FoodType) String() string {
	i -= 1
	if i >= FoodType(len(_FoodType_index)-1) {
		return "FoodType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _FoodType_name[_FoodType_index[i]:_FoodType_index[i+1]]
}
