// Code generated by "stringer -type=PlayerBytes -trimprefix=PlayerBytes"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PlayerBytesTrackStealthed-2]
	_ = x[PlayerBytesReleaseTimer-8]
	_ = x[PlayerBytesNoReleaseWindow-16]
}

const (
	_PlayerBytes_name_0 = "TrackStealthed"
	_PlayerBytes_name_1 = "ReleaseTimer"
	_PlayerBytes_name_2 = "NoReleaseWindow"
)

func (i PlayerBytes) String() string {
	switch {
	case i == 2:
		return _PlayerBytes_name_0
	case i == 8:
		return _PlayerBytes_name_1
	case i == 16:
		return _PlayerBytes_name_2
	default:
		return "PlayerBytes(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
