// Code generated by "stringer -type=StandState -trimprefix=StandState"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StandStateStand-0]
	_ = x[StandStateSit-1]
	_ = x[StandStateSitChair-2]
	_ = x[StandStateSleep-3]
	_ = x[StandStateSitLowChair-4]
	_ = x[StandStateSitMediumChair-5]
	_ = x[StandStateSitHighChair-6]
	_ = x[StandStateDead-7]
	_ = x[StandStateKneel-8]
}

const _StandState_name = "StandSitSitChairSleepSitLowChairSitMediumChairSitHighChairDeadKneel"

var _StandState_index = [...]uint8{0, 5, 8, 16, 21, 32, 46, 58, 62, 67}

func (i StandState) String() string {
	if i >= StandState(len(_StandState_index)-1) {
		return "StandState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StandState_name[_StandState_index[i]:_StandState_index[i+1]]
}
