// Code generated by "stringer -type=BagFamily -trimprefix=BagFamily"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BagFamilyNone-1]
	_ = x[BagFamilyArrows-1]
	_ = x[BagFamilyBullets-2]
	_ = x[BagFamilySoulShards-3]
	_ = x[BagFamilyUnknown1-4]
	_ = x[BagFamilyUnknown2-5]
	_ = x[BagFamilyHerbs-6]
	_ = x[BagFamilyEnchantingSupport-7]
	_ = x[BagFamilyEngineeringSupport-8]
	_ = x[BagFamilyKeys-9]
}

const _BagFamily_name = "NoneBulletsSoulShardsUnknown1Unknown2HerbsEnchantingSupportEngineeringSupportKeys"

var _BagFamily_index = [...]uint8{0, 4, 11, 21, 29, 37, 42, 59, 77, 81}

func (i BagFamily) String() string {
	i -= 1
	if i >= BagFamily(len(_BagFamily_index)-1) {
		return "BagFamily(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _BagFamily_name[_BagFamily_index[i]:_BagFamily_index[i+1]]
}
