// Code generated by "stringer -type=Bonding -trimprefix=Bonding"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BondingNone-0]
	_ = x[BondingWhenPickedUp-1]
	_ = x[BondingWhenEquipped-2]
	_ = x[BondingOnUse-3]
	_ = x[BondingQuestItem-4]
}

const _Bonding_name = "NoneWhenPickedUpWhenEquippedOnUseQuestItem"

var _Bonding_index = [...]uint8{0, 4, 16, 28, 33, 42}

func (i Bonding) String() string {
	if i >= Bonding(len(_Bonding_index)-1) {
		return "Bonding(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Bonding_name[_Bonding_index[i]:_Bonding_index[i+1]]
}
