// Code generated by "stringer -type=Class -trimprefix=Class"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ClassWarrior-1]
	_ = x[ClassPaladin-2]
	_ = x[ClassHunter-3]
	_ = x[ClassRouge-4]
	_ = x[ClassPriest-5]
	_ = x[ClassShaman-7]
	_ = x[ClassMage-8]
	_ = x[ClassWarlock-9]
	_ = x[ClassDruid-11]
}

const (
	_Class_name_0 = "WarriorPaladinHunterRougePriest"
	_Class_name_1 = "ShamanMageWarlock"
	_Class_name_2 = "Druid"
)

var (
	_Class_index_0 = [...]uint8{0, 7, 14, 20, 25, 31}
	_Class_index_1 = [...]uint8{0, 6, 10, 17}
)

func (i Class) String() string {
	switch {
	case 1 <= i && i <= 5:
		i -= 1
		return _Class_name_0[_Class_index_0[i]:_Class_index_0[i+1]]
	case 7 <= i && i <= 9:
		i -= 7
		return _Class_name_1[_Class_index_1[i]:_Class_index_1[i+1]]
	case i == 11:
		return _Class_name_2
	default:
		return "Class(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
