// Code generated by "stringer -type=ItemSubClass -trimprefix=ItemSubClass"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ItemSubClassConsumable-0]
	_ = x[ItemSubClassConsumablePotion-1]
	_ = x[ItemSubClassConsumableElixir-2]
	_ = x[ItemSubClassConsumableFlask-3]
	_ = x[ItemSubClassConsumableScroll-4]
	_ = x[ItemSubClassConsumableFood-5]
	_ = x[ItemSubClassConsumableItemEnhancement-6]
	_ = x[ItemSubClassConsumableBandage-7]
	_ = x[ItemSubClassConsumableOther-8]
	_ = x[ItemSubClassContainer-0]
	_ = x[ItemSubClassContainerSoul-1]
	_ = x[ItemSubClassContainerHerb-2]
	_ = x[ItemSubClassContainerEnchanting-3]
	_ = x[ItemSubClassContainerEngineering-4]
	_ = x[ItemSubClassWeaponAxe-0]
	_ = x[ItemSubClassWeaponAxe2-1]
	_ = x[ItemSubClassWeaponBow-2]
	_ = x[ItemSubClassWeaponGun-3]
	_ = x[ItemSubClassWeaponMace-4]
	_ = x[ItemSubClassWeaponMace2-5]
	_ = x[ItemSubClassWeaponPolearm-6]
	_ = x[ItemSubClassWeaponSword-7]
	_ = x[ItemSubClassWeaponSword2-8]
	_ = x[ItemSubClassWeaponStaff-10]
	_ = x[ItemSubClassWeaponFist-13]
	_ = x[ItemSubClassWeaponMisc-14]
	_ = x[ItemSubClassWeaponDagger-15]
	_ = x[ItemSubClassWeaponThrown-16]
	_ = x[ItemSubClassWeaponSpear-17]
	_ = x[ItemSubClassWeaponCrossbow-18]
	_ = x[ItemSubClassWeaponWand-19]
	_ = x[ItemSubClassWeaponFishingPole-20]
	_ = x[ItemSubClassArmorMisc-0]
	_ = x[ItemSubClassArmorCloth-1]
	_ = x[ItemSubClassArmorLeather-2]
	_ = x[ItemSubClassArmorMail-3]
	_ = x[ItemSubClassArmorPlate-4]
	_ = x[ItemSubClassArmorBuckler-5]
	_ = x[ItemSubClassArmorShield-6]
	_ = x[ItemSubClassArmorLibram-7]
	_ = x[ItemSubClassArmorIdol-8]
	_ = x[ItemSubClassArmorTotem-9]
	_ = x[ItemSubClassReagent-0]
	_ = x[ItemSubClassProjectileArrow-2]
	_ = x[ItemSubClassProjectileBullet-3]
	_ = x[ItemSubClassTradeGoods-0]
	_ = x[ItemSubClassTradeGoodsParts-1]
	_ = x[ItemSubClassTradeGoodsExplosives-2]
	_ = x[ItemSubClassTradeGoodsDevices-3]
	_ = x[ItemSubClassRecipeBook-0]
	_ = x[ItemSubClassRecipeLeatherworkingPattern-1]
	_ = x[ItemSubClassRecipeTailoringPattern-2]
	_ = x[ItemSubClassRecipeEngineeringSchematic-3]
	_ = x[ItemSubClassRecipeBlacksmithing-4]
	_ = x[ItemSubClassRecipeCookingRecipe-5]
	_ = x[ItemSubClassRecipeAlchemyRecipe-6]
	_ = x[ItemSubClassRecipeFirstAidManual-7]
	_ = x[ItemSubClassRecipeEnchantingFormula-8]
	_ = x[ItemSubClassRecipeFishingManual-9]
	_ = x[ItemSubClassQuiver-2]
	_ = x[ItemSubClassAmmoPouch-3]
	_ = x[ItemSubClassQuest-0]
	_ = x[ItemSubClassKey-0]
	_ = x[ItemSubClassKeyLockpick-1]
	_ = x[ItemSubClassPermanent-0]
	_ = x[ItemSUbClassJunk-0]
}

const (
	_ItemSubClass_name_0 = "ConsumableConsumablePotionConsumableElixirConsumableFlaskConsumableScrollConsumableFoodConsumableItemEnhancementConsumableBandageConsumableOtherArmorTotemWeaponStaff"
	_ItemSubClass_name_1 = "WeaponFistWeaponMiscWeaponDaggerWeaponThrownWeaponSpearWeaponCrossbowWeaponWandWeaponFishingPole"
)

var (
	_ItemSubClass_index_0 = [...]uint8{0, 10, 26, 42, 57, 73, 87, 112, 129, 144, 154, 165}
	_ItemSubClass_index_1 = [...]uint8{0, 10, 20, 32, 44, 55, 69, 79, 96}
)

func (i ItemSubClass) String() string {
	switch {
	case 0 <= i && i <= 10:
		return _ItemSubClass_name_0[_ItemSubClass_index_0[i]:_ItemSubClass_index_0[i+1]]
	case 13 <= i && i <= 20:
		i -= 13
		return _ItemSubClass_name_1[_ItemSubClass_index_1[i]:_ItemSubClass_index_1[i+1]]
	default:
		return "ItemSubClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
