// Code generated by "stringer -type=ItemFlag -trimprefix=ItemFlag"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ItemFlagNone-0]
	_ = x[ItemFlagBound-1]
	_ = x[ItemFlagUnlocked-4]
	_ = x[ItemFlagWrapped-8]
	_ = x[ItemFlagReadable-512]
}

const (
	_ItemFlag_name_0 = "NoneBound"
	_ItemFlag_name_1 = "Unlocked"
	_ItemFlag_name_2 = "Wrapped"
	_ItemFlag_name_3 = "Readable"
)

var (
	_ItemFlag_index_0 = [...]uint8{0, 4, 9}
)

func (i ItemFlag) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _ItemFlag_name_0[_ItemFlag_index_0[i]:_ItemFlag_index_0[i+1]]
	case i == 4:
		return _ItemFlag_name_1
	case i == 8:
		return _ItemFlag_name_2
	case i == 512:
		return _ItemFlag_name_3
	default:
		return "ItemFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
