// Code generated by "stringer -type=ItemQuality -trimprefix=ItemQuality"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ItemQualityPoor-0]
	_ = x[ItemQualityNormal-1]
	_ = x[ItemQualityUncommon-2]
	_ = x[ItemQualityRare-3]
	_ = x[ItemQualityEpic-4]
	_ = x[ItemQualityLegendary-5]
	_ = x[ItemQualityArtifact-6]
}

const _ItemQuality_name = "PoorNormalUncommonRareEpicLegendaryArtifact"

var _ItemQuality_index = [...]uint8{0, 4, 10, 18, 22, 26, 35, 43}

func (i ItemQuality) String() string {
	if i >= ItemQuality(len(_ItemQuality_index)-1) {
		return "ItemQuality(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ItemQuality_name[_ItemQuality_index[i]:_ItemQuality_index[i+1]]
}
