// Code generated by "stringer -type=PlayerFlag -trimprefix=PlayerFlag"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PlayerFlagsGroupLeader-1]
	_ = x[PlayerFlagsAFK-2]
	_ = x[PlayerFlagsDND-4]
	_ = x[PlayerFlagsGM-8]
	_ = x[PlayerFlagsGhost-16]
	_ = x[PlayerFlagsResting-32]
	_ = x[PlayerFlagsFFAPVP-128]
	_ = x[PlayerFlagsContestedPVP-256]
	_ = x[PlayerFlagsInPVP-512]
	_ = x[PlayerFlagsHideHelm-1024]
	_ = x[PlayerFlagsHideCloak-2048]
	_ = x[PlayerFlagsPartialPlayTime-4096]
	_ = x[PlayerFlagsNoPlayTime-8192]
	_ = x[PlayerFlagsSanctuary-65536]
	_ = x[PlayerFlagsTaxiBenchmark-131072]
	_ = x[PlayerFlagsPVPTimer-262144]
}

const _PlayerFlag_name = "sGroupLeadersAFKsDNDsGMsGhostsRestingsFFAPVPsContestedPVPsInPVPsHideHelmsHideCloaksPartialPlayTimesNoPlayTimesSanctuarysTaxiBenchmarksPVPTimer"

var _PlayerFlag_map = map[PlayerFlag]string{
	1:      _PlayerFlag_name[0:12],
	2:      _PlayerFlag_name[12:16],
	4:      _PlayerFlag_name[16:20],
	8:      _PlayerFlag_name[20:23],
	16:     _PlayerFlag_name[23:29],
	32:     _PlayerFlag_name[29:37],
	128:    _PlayerFlag_name[37:44],
	256:    _PlayerFlag_name[44:57],
	512:    _PlayerFlag_name[57:63],
	1024:   _PlayerFlag_name[63:72],
	2048:   _PlayerFlag_name[72:82],
	4096:   _PlayerFlag_name[82:98],
	8192:   _PlayerFlag_name[98:109],
	65536:  _PlayerFlag_name[109:119],
	131072: _PlayerFlag_name[119:133],
	262144: _PlayerFlag_name[133:142],
}

func (i PlayerFlag) String() string {
	if str, ok := _PlayerFlag_map[i]; ok {
		return str
	}
	return "PlayerFlag(" + strconv.FormatInt(int64(i), 10) + ")"
}
