// Code generated by "stringer -type=SpellCategory -trimprefix=SpellCategory"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SpellCategoryHealthManaPotions-4]
	_ = x[SpellCategoryDevourMagic-12]
}

const (
	_SpellCategory_name_0 = "HealthManaPotions"
	_SpellCategory_name_1 = "DevourMagic"
)

func (i SpellCategory) String() string {
	switch {
	case i == 4:
		return _SpellCategory_name_0
	case i == 12:
		return _SpellCategory_name_1
	default:
		return "SpellCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
