// Code generated by "stringer -type=SpellSchool -trimprefix=SpellSchool"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SpellSchoolPhysical-0]
	_ = x[SpellSchoolHoly-1]
	_ = x[SpellSchoolFire-2]
	_ = x[SpellSchoolNature-3]
	_ = x[SpellSchoolFrost-4]
	_ = x[SpellSchoolShadow-5]
	_ = x[SpellSchoolArcane-6]
}

const _SpellSchool_name = "PhysicalHolyFireNatureFrostShadowArcane"

var _SpellSchool_index = [...]uint8{0, 8, 12, 16, 22, 27, 33, 39}

func (i SpellSchool) String() string {
	if i >= SpellSchool(len(_SpellSchool_index)-1) {
		return "SpellSchool(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SpellSchool_name[_SpellSchool_index[i]:_SpellSchool_index[i+1]]
}
