// Code generated by "stringer -type=Stat -trimprefix=Stat"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatStrength-0]
	_ = x[StatAgility-1]
	_ = x[StatStamina-2]
	_ = x[StatIntellect-3]
	_ = x[StatSpirit-4]
}

const _Stat_name = "StrengthAgilityStaminaIntellectSpirit"

var _Stat_index = [...]uint8{0, 8, 15, 22, 31, 37}

func (i Stat) String() string {
	if i >= Stat(len(_Stat_index)-1) {
		return "Stat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Stat_name[_Stat_index[i]:_Stat_index[i+1]]
}
