// Code generated by "stringer -type=UpdateFlags -trimprefix=UpdateFlags"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UpdateFlagsNone-0]
	_ = x[UpdateFlagsSelf-1]
	_ = x[UpdateFlagsTransport-2]
	_ = x[UpdateFlagsFullGUID-4]
	_ = x[UpdateFlagsHighGUID-8]
	_ = x[UpdateFlagsAll-16]
	_ = x[UpdateFlagsLiving-32]
	_ = x[UpdateFlagsHasPosition-64]
}

const (
	_UpdateFlags_name_0 = "NoneSelfTransport"
	_UpdateFlags_name_1 = "FullGUID"
	_UpdateFlags_name_2 = "HighGUID"
	_UpdateFlags_name_3 = "All"
	_UpdateFlags_name_4 = "Living"
	_UpdateFlags_name_5 = "HasPosition"
)

var (
	_UpdateFlags_index_0 = [...]uint8{0, 4, 8, 17}
)

func (i UpdateFlags) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _UpdateFlags_name_0[_UpdateFlags_index_0[i]:_UpdateFlags_index_0[i+1]]
	case i == 4:
		return _UpdateFlags_name_1
	case i == 8:
		return _UpdateFlags_name_2
	case i == 16:
		return _UpdateFlags_name_3
	case i == 32:
		return _UpdateFlags_name_4
	case i == 64:
		return _UpdateFlags_name_5
	default:
		return "UpdateFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
