// Code generated by "stringer -type=LoginErrorCode"; DO NOT EDIT.

package packet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LoginOK-0]
	_ = x[LoginFailed-1]
	_ = x[LoginFailed2-2]
	_ = x[LoginBanned-3]
	_ = x[LoginUnknownAccount-4]
	_ = x[LoginUnknownAccount3-5]
	_ = x[LoginAlreadyOnline-6]
	_ = x[LoginNoTime-7]
	_ = x[LoginDBBusy-8]
	_ = x[LoginBadVersion-9]
	_ = x[LoginDownloadFile-10]
	_ = x[LoginFailed3-11]
	_ = x[LoginSuspended-12]
	_ = x[LoginFailed4-13]
	_ = x[LoginConnected-14]
	_ = x[LoginParentalControl-15]
	_ = x[LoginLockedEnforced-16]
}

const _LoginErrorCode_name = "LoginOKLoginFailedLoginFailed2LoginBannedLoginUnknownAccountLoginUnknownAccount3LoginAlreadyOnlineLoginNoTimeLoginDBBusyLoginBadVersionLoginDownloadFileLoginFailed3LoginSuspendedLoginFailed4LoginConnectedLoginParentalControlLoginLockedEnforced"

var _LoginErrorCode_index = [...]uint8{0, 7, 18, 30, 41, 60, 80, 98, 109, 120, 135, 152, 164, 178, 190, 204, 224, 243}

func (i LoginErrorCode) String() string {
	if i >= LoginErrorCode(len(_LoginErrorCode_index)-1) {
		return "LoginErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LoginErrorCode_name[_LoginErrorCode_index[i]:_LoginErrorCode_index[i+1]]
}
