// Code generated by "stringer -type=OpCode -trimprefix=OpCode"; DO NOT EDIT.

package packet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpCodeLoginChallenge-0]
	_ = x[OpCodeLoginProof-1]
	_ = x[OpCodeRealmlist-16]
}

const (
	_OpCode_name_0 = "LoginChallengeLoginProof"
	_OpCode_name_1 = "Realmlist"
)

var (
	_OpCode_index_0 = [...]uint8{0, 14, 24}
)

func (i OpCode) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _OpCode_name_0[_OpCode_index_0[i]:_OpCode_index_0[i+1]]
	case i == 16:
		return _OpCode_name_1
	default:
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
